# Generated by Django 5.2.8 on 2025-11-23 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                
                ('tipo', models.CharField(choices=[('declaracao_militar', 'Declaração Militar'), ('cedula_militar', 'Cédula Militar'), ('recibo_recenseamento', 'Recibo de Recenseamento Militar')], max_length=50)),
                ('destino', models.CharField(blank=True, max_length=200, null=True)),
                ('finalidade', models.CharField(blank=True, max_length=200, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('numero_sequencial', models.PositiveIntegerField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
