# Generated by Django 5.2.8 on 2025-12-14 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recenseamento', '0001_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recenseamento',
            name='bi',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recenseamento',
            name='foi_submetido_exame',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recenseamento',
            name='foto_capturada',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/'),
        ),
        migrations.AddField(
            model_name='recenseamento',
            name='resultado_exame',
            field=models.CharField(blank=True, choices=[('apto', 'Apto'), ('inapto', 'Inapto')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recenseamento',
            name='documento_identidade',
            field=models.FileField(blank=True, null=True, upload_to='documentos_identidade_uploads/'),
        ),
        migrations.CreateModel(
            name='PerfilCidadao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bi', models.FileField(blank=True, null=True, upload_to='documentos/bi/')),
                ('foto', models.ImageField(upload_to='perfil_fotos/')),
                ('dados_confirmados', models.BooleanField(default=False)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nome_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_bi', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
