# Generated by Django 5.2.8 on 2025-12-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recenseamento', '0002_recenseamento_bi_recenseamento_foi_submetido_exame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcidadao',
            name='email',
            field=models.EmailField(max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilcidadao',
            name='telefone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
