# Generated by Django 5.2.8 on 2025-12-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recenseamento', '0003_perfilcidadao_email_perfilcidadao_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcidadao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_fotos/'),
        ),
    ]
